rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :areas, only: [:index, :show], param: :i_j do
    collection do
      get :mcmap
      get :user_list
    end
    member do
      get :obj
      post :teleport
      post :add_demo_account
      post :remove_demo_account
    end
  end
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/area.rb
class Area < ActiveRecord::Base
  has_many :demo_accounts, inverse_of: :area, dependent: :destroy
  has_one :area_cached_obj, inverse_of: :area, dependent: :destroy
  USERS_PER_AREA = 4

  def to_param
    "#{coord_i}_#{coord_j}"
  end

  def usernames
    demo_accounts.map &:username
  end

  def add_demo_account name
    demo_account = demo_accounts.where(username: name).first_or_create
    user_accounts = DemoAccount.where(username: name).order(id: :asc).to_a
    user_accounts.shift.destroy while user_accounts.size > 1
    area_accounts = reload.demo_accounts.order(id: :asc).to_a
    area_accounts.shift.destroy while area_accounts.size > USERS_PER_AREA
    Area.notify_update
    demo_account
  end

  def remove_demo_account name
    demo_accounts.where(username: name).destroy_all
    Area.notify_update
  end

  def self.user_list
    Area.includes(:demo_accounts).map { |a|
      [a.to_param, a.usernames]
    }.sort_by(&:first).to_h
  end

  def self.notify_update
    Mcapi.update_user_list user_list
  end

  def self.prepare
    coords = Mcapi.user_list.keys.map { |k| k.split('_').map(&:to_i) }
    existing_areas = Area.all.index_by { |a| [a.coord_i, a.coord_j] }
    areas = coords.map do |i, j|
      existing_areas[[i,j]] || Area.create(coord_i: i, coord_j: j)
    end
    Area.where.not(id: areas).destroy_all
  end
end

rails/app/models/area_cached_obj.rb
class AreaCachedObj < ActiveRecord::Base
  belongs_to :area, inverse_of: :area_cached_obj
end

rails/app/models/demo_account.rb
class DemoAccount < ActiveRecord::Base
  belongs_to :area, inverse_of: :demo_accounts
  validates :username, format: { with: /\A[a-zA-Z0-9_.-]+\z/ }, length: { maximum: 32 }
  before_validation on: :create do
    api_response = Net::HTTP.get URI.parse("https://api.mojang.com/users/profiles/minecraft/#{username}")
    errors[:username] << 'not in mojang' unless api_response
  end
end

rails/app/models/mcapi.rb
class Mcapi
  def self.teleport
  end

  def self.ip
    ENV['MCPRINT_SERVER_IP'] || 'localhost'
  end

  def self.endpoint path=nil
    "http://#{ip}:4567/#{path}"
  end

  def self.objfile i, j
    api_get 'obj', area_id: "#{i}_#{j}"
  end

  def self.user_list
    JSON.parse api_get('user_list')
  end

  def self.teleport area_id:, username:
    api_post 'tp', area_id: area_id, user_id: username
  end

  def self.mcmap
    @map ||= api_get 'mcmap.png'
  end

  def self.update_user_list userlist
    api_post 'user_list', user_list: userlist
  end

  private

  def self.register
    url = "http://#{ENV['SERVER_HOSTNAME'] || 'localhost:3000'}/areas/user_list"
    api_post 'register', fetch_url: url
  end

  def self.token
    ENV['MCPRINT_SERVER_TOKEN'] || 'dev_token'
  end

  def self.api_get path, params={}
    path += "?#{params.merge(_token: token).to_param}"
    Net::HTTP.get URI.parse(endpoint(path))
  end

  def self.api_post path, params={}
    Net::HTTP.post(
      URI.parse(endpoint(path)),
      params.merge(_token: token).to_json,
      content_type: 'application/json'
    )
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, except: [:index, :mcmap, :user_list]
  def index
    @areas = Area.includes(:demo_accounts)
  end

  def teleport
    Mcapi.teleport area_id: @area.to_param, username: params[:username]
    render nothing: true
  end

  def add_demo_account
    demo_account = @area.add_demo_account params[:username]
    if demo_account.errors.any?
      redirect_to @area, notice: demo_account.errors.full_messages.join("\n")
    else
      redirect_to @area
    end
  end

  def remove_demo_account
    @area.remove_demo_account params[:username]
    redirect_to @area
  end

  def user_list
    render json: Area.user_list
  end

  def mcmap
    send_data Mcapi.mcmap, disposition: 'inline', type: 'image/png'
  end

  def obj
    if params[:cache].to_s == 'false' || @area.area_cached_obj.nil? || @area.area_cached_obj.updated_at < 10.minutes.ago
      @area.area_cached_obj ||= AreaCachedObj.new
      @area.area_cached_obj.obj_data = Mcapi.objfile @area.coord_i, @area.coord_j
      @area.area_cached_obj.save
      @area.area_cached_obj.touch
    end
    send_data @area.area_cached_obj.obj_data, filename: "block_#{@area.to_param}.obj"
  end

  private

  def set_area
    i, j = params[:i_j].split('_')
    @area = Area.find_by! coord_i: i, coord_j: j
  end
end

rails/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    
  end

  def map

  end

end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/views/areas/index.html.slim
h4.mdl-grid
  .mdl-cell.mdl-cell--2-col
    = link_to root_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored"
      i.material-icons reply
      | 戻る
  .mdl-cell.mdl-cell--8-col
    center
      .cube data-color={r:0.6,g:0.7,b:1}.to_json style='width:36px;height:36px;'
      | エリアを選んでください

.mcmap-container
  .search-field.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
    input.mdl-textfield__input#keyword_search type='text'
    label.mdl-textfield__label for='keyword_search' search by area_id(xx_yy) or username
  #mcmap
    .background style='background-image: url(/areas/mcmap.png)'
    - @areas.each do |area|
      - data = { area_id: area.to_param, keywords: area.usernames.join(' ') }
      - style = "left: #{area.coord_i*100/32.0}%; top: #{area.coord_j*100/32.0}%"
      = link_to area, class: 'area', id: "area_#{area.to_param}", style: style, data: data do
        .area-button
          = area.demo_accounts.empty? ? '' : "#{area.demo_accounts.size}/#{Area::USERS_PER_AREA}"
          .mdl-tooltip data-mdl-for="area_#{area.to_param}"
            | Area #{area.to_param}
            - if area.usernames.present?
              div = area.usernames.join(' ')

rails/app/views/areas/show.html.slim
h4.mdl-grid
  .mdl-cell.mdl-cell--2-col
    = link_to areas_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored"
      i.material-icons reply
      | 戻る
  .mdl-cell.mdl-cell--8-col
    center
      .cube data-color={r:0.6,g:0.7,b:1}.to_json style='width:36px;height:36px;'
      | エリア #{@area.to_param}

.mdl-grid
  .mdl-cell.mdl-cell--6-col
    #preview.left-panel data-objfile=obj_area_path(@area)
      .loading
        .mdl-spinner.mdl-js-spinner.is-active
      .menu-buttons
        button.mdl-button.mdl-js-button.mdl-js-ripple-effect#preview_reload data-objfile=obj_area_path(@area, cache: false) reload
        button.mdl-button.mdl-js-button#download_menu.mdl-js-ripple-effect
          | Download
        ul.mdl-menu.mdl-menu--top-right.mdl-js-menu.mdl-js-ripple-effect for="download_menu"
          a href=obj_area_path(@area, cache: false, rand: rand)
            li.mdl-menu__item
              | Download OBJ
          a href='/block.mtl' download='block.mtl'
            li.mdl-menu__item
              | Download MTL
          a href='/texture.png' download='texture.png'
            li.mdl-menu__item
              | Download Texture

  .mdl-cell.mdl-cell--6-col.right-panel
    - if @area.demo_accounts.empty?
      .mdl-cell.mdl-cell--12-col 遊ぶ前にあなたのusernameをこのエリアに追加してください
    - else
      table.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp.mdl-cell.mdl-cell--12-col
        thead
          tr
            th.mdl-data-table__cell--non-numeric username
            th
            th
        tbody
          - @area.demo_accounts.sort_by(&:username).each do |account|
            tr
              td.mdl-data-table__cell--non-numeric = account.username
              td
                = link_to teleport_area_path(@area, username: account.username), remote: true, method: :post, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect', id: "user_#{account.username}" do
                  | このエリアにテレポート
                  .mdl-tooltip data-mdl-for="user_#{account.username}"
                    div ワールド内で迷子になった時に
                    div クリックしてください
              td
                = link_to remove_demo_account_area_path(@area, username: account.username), method: :post, data: {confirm: '本当に削除しますか'}, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' do
                  i.material-icons delete

    = form_tag action: :add_demo_account, class: 'mdl-cell.mdl-cell--12-col' do
      div.mdl-textfield.mdl-js-textfield.mdl-cell.mdl-cell--6-col
        input.mdl-textfield__input type='text' pattern='[a-zA-Z0-9_.-]+' name='username' id='username'
        label.mdl-textfield__label for='username' minecraft username
        span.mdl-textfield__error invalid username
      input.mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.mdl-button--colored.mdl-cell.mdl-cell--6-col type='submit' value='このエリアに追加'

    .howto
      button.mdl-button.mdl-js-button.mdl-button--raised#play
        | このエリアで建築する

dialog.mdl-dialog#play_dialog
  h4.mdl-dialog__title このエリアで建築する
  .mdl-dialog__content
    | サーバアドレスは
    input.server-ip value=Mcapi.ip readonly=true
    | です
    br
    br
    - if @area.usernames.present?
      div
        | このエリアで建築できるユーザ:
        - @area.usernames.each do |name|
          span.username = name
      | この中にあなたのユーザ名がない場合は追加してください
      br
    - else
      | まず、あなたのマインクラフトのusernameをこのエリアに追加してください


  .mdl-dialog__actions
    button.mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.mdl-button--colored.close type="button"  OK

javascript:
  var dialog = document.querySelector('dialog');
  var showDialogButton = document.querySelector('#play');
  if (! dialog.showModal) {
    dialogPolyfill.registerDialog(dialog);
  }
  showDialogButton.addEventListener('click', function() {
    dialog.showModal();
  });
  dialog.querySelector('.close').addEventListener('click', function() {
    dialog.close();
  });

rails/app/views/layouts/application.html.slim
doctype html
html
  head
    title Mcprint
    = csrf_meta_tags

    meta name="turbolinks-cache-control" content="no-cache"
    link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"
    link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"
    script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.js'
    script defer=true src="https://code.getmdl.io/1.3.0/material.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        div class="flash-messages flash-messages-#{name}" = msg
    = yield

rails/app/views/top/index.html.slim
.top-header
  h1
    .icon
      .cube data-color={r:0.6,g:0.8,b:1}.to_json
      .cube data-color={r:0.6,g:0.9,b:1}.to_json
      .cube data-color={r:0.7,g:0.6,b:0.8}.to_json
    .title.main-title MC PRINT
    .title.sub-title マインクラフトで建築、3Dプリンタで印刷
center style='margin-bottom: 40px;'
  .mdl-tabs.mdl-js-tabs.mdl-js-ripple-effect
    .mdl-tabs__tab-bar
      a.mdl-tabs__tab.is-active href="#step1"  1.エリアを選ぶ
      a.mdl-tabs__tab href="#step2"  2.建築
      a.mdl-tabs__tab href="#step3"  3.ダウンロード
    #step1.howto-step.mdl-tabs__panel.is-active
      .slides
        .slide
          div 建築するエリアを選び
          = image_tag 'description/area.png', width: 480
        .slide style='display:none'
          div 自分のマインクラフトのユーザ名を追加
          = image_tag 'description/add.png', width: 480
    #step2.howto-step.mdl-tabs__panel
      .slides
        .slide
          div サーバにログイン
          = image_tag 'description/server.png', width: 480
        .slide style='display:none'
          div サーバにログイン
          = image_tag 'description/login.png', width: 480
        .slide style='display:none'
          div 枠の中に建築
          = image_tag 'description/build.png', width: 480
    #step3.howto-step.mdl-tabs__panel
      .slides
        .slide
          div Reloadを押して最新版をプレビュー
          = image_tag 'description/preview.png', width: 480
        .slide style='display:none'
          div 3Dデータをダウンロード
          = image_tag 'description/download.png', width: 480
  = link_to areas_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored getting-started-button'
    | 始める